export default {
    products: [{
        _id: '123',
        name: 'Slim Shirt',
        category: 'Shirts',
        image: 'https://www.alixbdanthenay.fr/wp-content/uploads/2015/07/Indispensable-4-1.jpg',
        price: 60,
        brand: 'Nike',
        rating: 4.5,
        availability: 'Only 5 left',
        numReviews: 10,
        countInStock: 6,
    },

    {
        _id: '456',
        name: 'Fit Shirt',
        category: 'Shirts',
        image: 'https://www.alixbdanthenay.fr/wp-content/uploads/2016/11/11.jpg',
        price: 40,
        brand: 'Nike',
        rating: 3.5,
        availability: 'Only 3 left',
        numReviews: 10,
        countInStock: 3,
    },

    {
        _id: '7',
        name: 'Best Pants',
        category: 'Pants',
        image: 'https://www.alixbdanthenay.fr/wp-content/uploads/2016/11/20mars17-sans-typo.jpg',
        price: 50,
        brand: 'Nike',
        rating: 4.2,
        availability: 'Available',
        numReviews: 10,
        countInStock: 7,
    },
    {
        _id: '8',
        name: 'Best Pants',
        category: 'Pants',
        image: 'https://www.alixbdanthenay.fr/wp-content/uploads/2016/11/20mars17-sans-typo.jpg',
        price: 50,
        brand: 'Nike',
        rating: 4.2,
        availability: 'Available',
        numReviews: 10,
        countInStock: 0,
    },
    {
        _id: '9',
        name: 'Best Pants',
        category: 'Pants',
        image: 'https://www.alixbdanthenay.fr/wp-content/uploads/2016/11/20mars17-sans-typo.jpg',
        price: 50,
        brand: 'Nike',
        availability: 'Available',
        rating: 4.2,
        numReviews: 10,
        countInStock: 3,
    }
]
}